import { mercedes, kia, chevrolet, honda, acura, bentley, bmw, bugatti, ford, hyundai, infiniti, jaguar, mazda, mitsubishi, peugeot, rangeRover, rollsRoyce, suzuki, toyota, volkswagen } from "../assets";

export const products = [
  {
    id: 1,
    productName: 'Mercedes',
    section: 'Top Sellers',
    productImage: mercedes,
    price: 50000,
  },
  {
    id: 2,
    productName: 'Kia',
    section: 'Recommended',
    productImage: kia,
    price: 54000,
  },
  {
    id: 3,
    productName: 'Chevrolet',
    section: 'Top Buyers',
    productImage: chevrolet,
    price: 70000,
  },
  {
    id: 4,
    productName: 'Honda',
    section: 'Top Losers',
    productImage: honda,
    price: 45000,
  },
  {
    id: 5,
    productName: 'Toyota',
    section: 'Top Gainers',
    productImage: toyota,
    price: 50000,
  },
  {
    id: 6,
    productName: 'Peugeot',
    section: 'Top Sellers',
    productImage: peugeot,
    price: 52500,
  },
  {
    id: 7,
    productName: 'Volkswagen',
    section: 'Recommended',
    productImage: volkswagen,
    price: 45000,
  },
  {
    id: 8,
    productName: 'Range Rover',
    section: 'Top Buyers',
    productImage: rangeRover,
    price: 50000,
  },
  {
    id: 9,
    productName: 'Hyundai',
    section: 'Top Losers',
    productImage: hyundai,
    price: 45000,
  },
  {
    id: 10,
    productName: 'Bugatti',
    section: 'Top Gainers',
    productImage: bugatti,
    price: 75000,
  },
  {
    id: 11,
    productName: 'Mazda',
    section: 'Top Sellers',
    productImage: mazda,
    price: 55000,
  },
  {
    id: 12,
    productName: 'Infiniti',
    section: 'Recommended',
    productImage: infiniti,
    price: 45000,
  },
  {
    id: 13,
    productName: 'Acura',
    section: 'Top Buyers',
    productImage: acura,
    price: 50000,
  },
  {
    id: 14,
    productName: 'Mitsubishi',
    section: 'Top Losers',
    productImage: mitsubishi,
    price: 52500,
  },
  {
    id: 15,
    productName: 'Ford',
    section: 'Top Gainers',
    productImage: ford,
    price: 39000,
  },
  {
    id: 16,
    productName: 'Jaguar',
    section: 'Top Sellers',
    productImage: jaguar,
    price: 48000,
  },
  {
    id: 17,
    productName: 'Bentley',
    section: 'Recommended',
    productImage: bentley,
    price: 45000,
  },
  {
    id: 18,
    productName: 'Suzuki',
    section: 'Top Buyers',
    productImage: suzuki,
    price: 50000,
  },
  {
    id: 19,
    productName: 'BMW',
    section: 'Top Losers',
    productImage: bmw,
    price: 47500,
  },
  {
    id: 20,
    productName: 'Rolls Royce',
    section: 'Top Gainers',
    productImage: rollsRoyce,
    price: 52500,
  },
];